/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ABUNASSAR PENARANDA
 */
public class VAsignarCandidato extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarRecordUtilidad
     */
    public VAsignarCandidato() {
        initComponents();
    }

    public JComboBox<String> getCmbRif() {
        return cmbRif;
    }

    public JTextField getTxtSalario() {
        return txtSalario;
    }

    public JButton getBtnAsignar() {
        return btnAsignar;
    }

    public JComboBox<String> getCmbProyecto() {
        return cmbProyecto;
    }

    public JComboBox<String> getCmbTipoMoneda() {
        return cmbTipoMoneda;
    }

    public JComboBox<String> getCmbTipoPago() {
        return cmbTipoPago;
    }

    public JScrollPane getScrollpanReporteProyecto1() {
        return scrollpanReporteProyecto1;
    }

    public JTable getTableReporteProyectos() {
        return tableReporteProyectos;
    }

    public JTable getTableReporteNoAsignados() {
        return tableReporteNoAsignados;
    }

    public JScrollPane getScrollpanReporteProyecto() {
        return scrollpanReporteProyecto;
    }

    public JTable getTableReporteNombres() {
        return tableReporteNoAsignados;
    }

    public JButton getBtnConsultarNombres() {
        return btnAsignar;
    }

    public JLabel getLblApellidos() {
        return lblSalario;
    }

    public JLabel getLblNombres() {
        return lblProyecto;
    }

    public JLabel getLblPalabrasClave() {
        return lblRif;
    }

    public ButtonGroup getBtngroupFiltrarPor() {
        return btngroupFiltrarPor;
    }

    public JPanel getPanConsultarUtilidad() {
        return panConsultarCandidatos;
    }
    
     public void Agregar_Listener(ActionListener ac)
   {
       this.btnAsignar.addActionListener(ac);
   }

     public void agregarItemListener(ItemListener il) {
         this.cmbRif.addItemListener(il);
         this.cmbProyecto.addItemListener(il);
         this.cmbTipoMoneda.addItemListener(il);
         this.cmbTipoPago.addItemListener(il);
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupFiltrarPor = new javax.swing.ButtonGroup();
        panConsultarCandidatos = new javax.swing.JPanel();
        lblNoAsignados = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        lblProyecto = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblRif = new javax.swing.JLabel();
        scrollpanReporteProyecto = new javax.swing.JScrollPane();
        tableReporteNoAsignados = new javax.swing.JTable();
        cmbRif = new javax.swing.JComboBox<>();
        scrollpanReporteProyecto1 = new javax.swing.JScrollPane();
        tableReporteProyectos = new javax.swing.JTable();
        lblProyectos = new javax.swing.JLabel();
        cmbProyecto = new javax.swing.JComboBox<>();
        cmbTipoMoneda = new javax.swing.JComboBox<>();
        lblTipoMoneda = new javax.swing.JLabel();
        lblTipoPago = new javax.swing.JLabel();
        cmbTipoPago = new javax.swing.JComboBox<>();
        txtSalario = new javax.swing.JTextField();
        jpanEncabezado1 = new javax.swing.JPanel();
        lblRegistrarCandidato1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panConsultarCandidatos.setBackground(new java.awt.Color(102, 102, 102));
        panConsultarCandidatos.setForeground(new java.awt.Color(102, 102, 102));
        panConsultarCandidatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoAsignados.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNoAsignados.setForeground(new java.awt.Color(255, 255, 255));
        lblNoAsignados.setText("Candidatos no asignados a un proyecto:");
        panConsultarCandidatos.add(lblNoAsignados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnAsignar.setBackground(new java.awt.Color(255, 153, 51));
        btnAsignar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAsignar.setText("Asignar");
        btnAsignar.setVisible(false);
        btnAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsignarMouseEntered(evt);
            }
        });
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        panConsultarCandidatos.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, -1));

        lblProyecto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblProyecto.setForeground(new java.awt.Color(255, 255, 255));
        lblProyecto.setText("Código de proyecto:");
        lblProyecto.setVisible(false);
        panConsultarCandidatos.add(lblProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        lblSalario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblSalario.setForeground(new java.awt.Color(255, 255, 255));
        lblSalario.setText("Salario:");
        panConsultarCandidatos.add(lblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, 20));
        lblSalario.setVisible(false);

        lblRif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblRif.setForeground(new java.awt.Color(255, 255, 255));
        lblRif.setText("RIF Candidato:");
        lblRif.setVisible(false);
        panConsultarCandidatos.add(lblRif, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 20));

        scrollpanReporteProyecto.setVisible(false);
        scrollpanReporteProyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tableReporteNoAsignados.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tableReporteNoAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanReporteProyecto.setViewportView(tableReporteNoAsignados);

        panConsultarCandidatos.add(scrollpanReporteProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 990, 120));

        cmbRif.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbRif.setMaximumRowCount(3);
        cmbRif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cmbRif.setFocusable(false);
        panConsultarCandidatos.add(cmbRif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        scrollpanReporteProyecto.setVisible(false);
        scrollpanReporteProyecto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tableReporteProyectos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tableReporteProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanReporteProyecto1.setViewportView(tableReporteProyectos);

        panConsultarCandidatos.add(scrollpanReporteProyecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 990, 120));

        lblProyectos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblProyectos.setForeground(new java.awt.Color(255, 255, 255));
        lblProyectos.setText("Proyectos disponibles:");
        panConsultarCandidatos.add(lblProyectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cmbProyecto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbProyecto.setMaximumRowCount(3);
        cmbProyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cmbProyecto.setFocusable(false);
        panConsultarCandidatos.add(cmbProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        cmbTipoMoneda.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbTipoMoneda.setMaximumRowCount(3);
        cmbTipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Bolívar", "Dólar", "Otro" }));
        cmbTipoMoneda.setFocusable(false);
        panConsultarCandidatos.add(cmbTipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));

        lblTipoMoneda.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTipoMoneda.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoMoneda.setText("Tipo de moneda:");
        lblProyecto.setVisible(false);
        panConsultarCandidatos.add(lblTipoMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        lblTipoPago.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTipoPago.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoPago.setText("Tipo de pago:");
        lblProyecto.setVisible(false);
        panConsultarCandidatos.add(lblTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        cmbTipoPago.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cmbTipoPago.setMaximumRowCount(3);
        cmbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Salario", "Horas" }));
        cmbTipoPago.setFocusable(false);
        panConsultarCandidatos.add(cmbTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        txtSalario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtSalario.setToolTipText("");
        panConsultarCandidatos.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 110, -1));

        getContentPane().add(panConsultarCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1019, 590));

        jpanEncabezado1.setBackground(new java.awt.Color(255, 153, 51));
        jpanEncabezado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarCandidato1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblRegistrarCandidato1.setText("ASIGNAR CANDIDATOS A UN PROYECTO");
        jpanEncabezado1.add(lblRegistrarCandidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 22, -1, -1));

        getContentPane().add(jpanEncabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1019, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblNoAsignados() {
        return lblNoAsignados;
    }

    public JLabel getLblProyecto() {
        return lblProyecto;
    }

    public JLabel getLblProyectos() {
        return lblProyectos;
    }

    public JLabel getLblRegistrarCandidato1() {
        return lblRegistrarCandidato1;
    }

    public JLabel getLblRif() {
        return lblRif;
    }

    public JLabel getLblSalario() {
        return lblSalario;
    }

    public JLabel getLblTipoMoneda() {
        return lblTipoMoneda;
    }

    public JLabel getLblTipoPago() {
        return lblTipoPago;
    }

    private void btnAsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAsignarMouseClicked

    private void btnAsignarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAsignarMouseEntered

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
      //  scrollpanReporteProyecto.setVisible(true);
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAsignarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAsignarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAsignarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAsignarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAsignarCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.ButtonGroup btngroupFiltrarPor;
    private javax.swing.JComboBox<String> cmbProyecto;
    private javax.swing.JComboBox<String> cmbRif;
    private javax.swing.JComboBox<String> cmbTipoMoneda;
    private javax.swing.JComboBox<String> cmbTipoPago;
    private javax.swing.JPanel jpanEncabezado1;
    private javax.swing.JLabel lblNoAsignados;
    private javax.swing.JLabel lblProyecto;
    private javax.swing.JLabel lblProyectos;
    private javax.swing.JLabel lblRegistrarCandidato1;
    private javax.swing.JLabel lblRif;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipoMoneda;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JPanel panConsultarCandidatos;
    private javax.swing.JScrollPane scrollpanReporteProyecto;
    private javax.swing.JScrollPane scrollpanReporteProyecto1;
    private javax.swing.JTable tableReporteNoAsignados;
    private javax.swing.JTable tableReporteProyectos;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
