/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ABUNASSAR PENARANDA
 */
public class VConsultaRecordPago extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarRecordPagos
     */
    public VConsultaRecordPago() {
        initComponents();
    }

    public JButton getBtnConsultarEmpleado() {
        return btnConsultarEmpleado;
    }

    public JButton getBtnConsultarMes() {
        return btnConsultarMes;
    }

    public JButton getBtnConsultarProyecto() {
        return btnConsultarProyecto;
    }

    public ButtonGroup getBtngroupFiltrarPor() {
        return btngroupFiltrarPor;
    }

    public JComboBox<String> getCmbboxEmpleadoConsultar() {
        return cmbboxEmpleadoConsultar;
    }

    public JComboBox<String> getCmbboxMesConsultar() {
        return cmbboxMesConsultar;
    }

    public JComboBox<String> getCmbboxProyectoConsultar() {
        return cmbboxProyectoConsultar;
    }

    public JLabel getLblFiltrarPor() {
        return lblFiltrarPor;
    }

    public JLabel getLblHorasLaborables() {
        return lblHorasLaborables;
    }

    public JLabel getLblMesConsultar() {
        return lblMesConsultar;
    }

    public JLabel getLblNombreEmpleadoConsultar() {
        return lblNombreEmpleadoConsultar;
    }

    public JLabel getLblNombreProyectoConsultar() {
        return lblNombreProyectoConsultar;
    }

    public JLabel getLblSalario() {
        return lblSalario;
    }

    public JLabel getLblTipoDeMoneda() {
        return lblTipoDeMoneda;
    }

    public JLabel getLblTipoDePago() {
        return lblTipoDePago;
    }

    public JPanel getPanRecordPagos() {
        return panRecordPagos;
    }

    public JRadioButton getRadiobtnEmpleado() {
        return radiobtnEmpleado;
    }

    public JRadioButton getRadiobtnMes() {
        return radiobtnMes;
    }

    public JRadioButton getRadiobtnProyecto() {
        return radiobtnProyecto;
    }

    public JScrollPane getScrollpanReporteEmpleado() {
        return scrollpanReporteEmpleado;
    }

    public JScrollPane getScrollpanReporteProyecto() {
        return scrollpanReporteProyecto;
    }

    public JScrollPane getScrollpaneReporteMes() {
        return scrollpanReporteMes;
    }

    public JTable getTableReporteEmpleado() {
        return tableReporteEmpleado;
    }

    public JTable getTableReporteMes() {
        return tableReporteMes;
    }

    public JTable getTableReporteProyecto() {
        return tableReporteProyecto;
    }

    public JTextField getTxtHorasLaborables() {
        return txtHorasLaborables;
    }

    public JTextField getTxtSalario() {
        return txtSalario;
    }

    public JTextField getTxtTipoDeMoneda() {
        return txtTipoDeMoneda;
    }

    public JTextField getTxtTipoDePago() {
        return txtTipoDePago;
    }
    
    
       public void Agregar_Listener(ActionListener ac)
   {
   
       this.radiobtnProyecto.addActionListener(ac);
       this.radiobtnMes.addActionListener(ac);
       this.radiobtnEmpleado.addActionListener(ac);
       this.cmbboxProyectoConsultar.addActionListener(ac);
       this.cmbboxMesConsultar.addActionListener(ac);
       this.cmbboxEmpleadoConsultar.addActionListener(ac);
       this.btnConsultarProyecto.addActionListener(ac);
       this.btnConsultarMes.addActionListener(ac);
       this.btnConsultarEmpleado.addActionListener(ac);
       
       
   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupFiltrarPor = new javax.swing.ButtonGroup();
        jpanEncabezado = new javax.swing.JPanel();
        lblRegistrarCandidato = new javax.swing.JLabel();
        panRecordPagos = new javax.swing.JPanel();
        lblFiltrarPor = new javax.swing.JLabel();
        radiobtnProyecto = new javax.swing.JRadioButton();
        radiobtnEmpleado = new javax.swing.JRadioButton();
        radiobtnMes = new javax.swing.JRadioButton();
        cmbboxProyectoConsultar = new javax.swing.JComboBox<>();
        btnConsultarProyecto = new javax.swing.JButton();
        lblNombreProyectoConsultar = new javax.swing.JLabel();
        lblNombreEmpleadoConsultar = new javax.swing.JLabel();
        cmbboxEmpleadoConsultar = new javax.swing.JComboBox<>();
        btnConsultarEmpleado = new javax.swing.JButton();
        scrollpanReporteProyecto = new javax.swing.JScrollPane();
        tableReporteProyecto = new javax.swing.JTable();
        scrollpanReporteEmpleado = new javax.swing.JScrollPane();
        tableReporteEmpleado = new javax.swing.JTable();
        txtSalario = new javax.swing.JTextField();
        txtTipoDePago = new javax.swing.JTextField();
        txtTipoDeMoneda = new javax.swing.JTextField();
        lblTipoDePago = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblTipoDeMoneda = new javax.swing.JLabel();
        lblMesConsultar = new javax.swing.JLabel();
        cmbboxMesConsultar = new javax.swing.JComboBox<>();
        btnConsultarMes = new javax.swing.JButton();
        lblHorasLaborables = new javax.swing.JLabel();
        txtHorasLaborables = new javax.swing.JTextField();
        scrollpanReporteMes = new javax.swing.JScrollPane();
        tableReporteMes = new javax.swing.JTable();
        jpanEncabezado1 = new javax.swing.JPanel();
        lblRegistrarCandidato1 = new javax.swing.JLabel();

        jpanEncabezado.setBackground(new java.awt.Color(255, 153, 51));

        lblRegistrarCandidato.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblRegistrarCandidato.setText("Gestionar candidato");

        javax.swing.GroupLayout jpanEncabezadoLayout = new javax.swing.GroupLayout(jpanEncabezado);
        jpanEncabezado.setLayout(jpanEncabezadoLayout);
        jpanEncabezadoLayout.setHorizontalGroup(
            jpanEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanEncabezadoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblRegistrarCandidato)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanEncabezadoLayout.setVerticalGroup(
            jpanEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanEncabezadoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRegistrarCandidato)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panRecordPagos.setBackground(new java.awt.Color(102, 102, 102));
        panRecordPagos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panRecordPagos.setForeground(new java.awt.Color(204, 204, 204));
        panRecordPagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFiltrarPor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFiltrarPor.setForeground(new java.awt.Color(255, 255, 255));
        lblFiltrarPor.setText("Filtrar por:");
        lblFiltrarPor.setFocusable(false);
        panRecordPagos.add(lblFiltrarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 38, -1, -1));

        radiobtnProyecto.setBackground(new java.awt.Color(102, 102, 102));
        btngroupFiltrarPor.add(radiobtnProyecto);
        radiobtnProyecto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radiobtnProyecto.setForeground(new java.awt.Color(255, 255, 255));
        radiobtnProyecto.setText("Proyecto");
        radiobtnProyecto.setFocusable(false);
        radiobtnProyecto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiobtnProyectoStateChanged(evt);
            }
        });
        radiobtnProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnProyectoMouseClicked(evt);
            }
        });
        radiobtnProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnProyectoActionPerformed(evt);
            }
        });
        //radiobtnProyecto.setSelected(true);
        panRecordPagos.add(radiobtnProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 56, -1, -1));

        radiobtnEmpleado.setBackground(new java.awt.Color(102, 102, 102));
        btngroupFiltrarPor.add(radiobtnEmpleado);
        radiobtnEmpleado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radiobtnEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        radiobtnEmpleado.setText("Empleado");
        radiobtnEmpleado.setFocusable(false);
        radiobtnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnEmpleadoMouseClicked(evt);
            }
        });
        panRecordPagos.add(radiobtnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 56, -1, -1));

        radiobtnMes.setBackground(new java.awt.Color(102, 102, 102));
        btngroupFiltrarPor.add(radiobtnMes);
        radiobtnMes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radiobtnMes.setForeground(new java.awt.Color(255, 255, 255));
        radiobtnMes.setText("Mes");
        radiobtnMes.setFocusable(false);
        radiobtnMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnMesMouseClicked(evt);
            }
        });
        panRecordPagos.add(radiobtnMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 56, -1, -1));

        cmbboxProyectoConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbboxProyectoConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "1", "2" }));
        cmbboxProyectoConsultar.setVisible(false);
        cmbboxProyectoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxProyectoConsultarActionPerformed(evt);
            }
        });
        cmbboxProyectoConsultar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbboxProyectoConsultarPropertyChange(evt);
            }
        });
        panRecordPagos.add(cmbboxProyectoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 300, 20));

        btnConsultarProyecto.setBackground(new java.awt.Color(255, 153, 51));
        btnConsultarProyecto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConsultarProyecto.setText("Consultar");
        btnConsultarProyecto.setBorderPainted(false);
        btnConsultarProyecto.setVisible(false);
        btnConsultarProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarProyectoMouseEntered(evt);
            }
        });
        btnConsultarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProyectoActionPerformed(evt);
            }
        });
        panRecordPagos.add(btnConsultarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblNombreProyectoConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreProyectoConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProyectoConsultar.setText("Nombre del proyecto a consultar:");
        lblNombreProyectoConsultar.setFocusable(false);
        lblNombreProyectoConsultar.setVisible(false);
        panRecordPagos.add(lblNombreProyectoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblNombreEmpleadoConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreEmpleadoConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreEmpleadoConsultar.setText("Seleccionar el nombre del empleado a consultar:");
        lblNombreEmpleadoConsultar.setFocusable(false);
        lblNombreEmpleadoConsultar.setVisible(false);
        panRecordPagos.add(lblNombreEmpleadoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmbboxEmpleadoConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbboxEmpleadoConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "1", "2" }));
        cmbboxEmpleadoConsultar.setVisible(false);
        cmbboxEmpleadoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxEmpleadoConsultarActionPerformed(evt);
            }
        });
        cmbboxEmpleadoConsultar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbboxEmpleadoConsultarPropertyChange(evt);
            }
        });
        panRecordPagos.add(cmbboxEmpleadoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 300, 20));

        btnConsultarEmpleado.setBackground(new java.awt.Color(255, 153, 0));
        btnConsultarEmpleado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConsultarEmpleado.setText("Consultar");
        btnConsultarEmpleado.setFocusable(false);
        btnConsultarEmpleado.setVisible(false);
        btnConsultarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarEmpleadoMouseEntered(evt);
            }
        });
        btnConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpleadoActionPerformed(evt);
            }
        });
        panRecordPagos.add(btnConsultarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        scrollpanReporteProyecto.setVisible(false);

        tableReporteProyecto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableReporteProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Horas trabajadas", "Salario", "Tipo de pago", "Monto pagado", "Tipo de moneda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanReporteProyecto.setViewportView(tableReporteProyecto);

        panRecordPagos.add(scrollpanReporteProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 990, 390));

        scrollpanReporteEmpleado.setVisible(false);
        scrollpanReporteEmpleado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tableReporteEmpleado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableReporteEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mes", "Horas trabajadas", "Monto pagado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanReporteEmpleado.setViewportView(tableReporteEmpleado);

        panRecordPagos.add(scrollpanReporteEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 990, 380));

        txtSalario.setEditable(false);
        txtSalario.setBackground(new java.awt.Color(204, 204, 204));
        txtSalario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSalario.setFocusable(false);
        txtSalario.setVisible(false);
        panRecordPagos.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, -1));

        txtTipoDePago.setEditable(false);
        txtTipoDePago.setBackground(new java.awt.Color(204, 204, 204));
        txtTipoDePago.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtTipoDePago.setFocusable(false);
        txtTipoDePago.setVisible(false);
        panRecordPagos.add(txtTipoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 70, -1));

        txtTipoDeMoneda.setEditable(false);
        txtTipoDeMoneda.setBackground(new java.awt.Color(204, 204, 204));
        txtTipoDeMoneda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtTipoDeMoneda.setFocusable(false);
        txtTipoDeMoneda.setVisible(false);
        panRecordPagos.add(txtTipoDeMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 70, -1));

        lblTipoDePago.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTipoDePago.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoDePago.setText("Tipo de pago:");
        lblTipoDePago.setFocusable(false);
        panRecordPagos.add(lblTipoDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 20));
        lblTipoDePago.setVisible(false);

        lblSalario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSalario.setForeground(new java.awt.Color(255, 255, 255));
        lblSalario.setText("Salario:");
        lblSalario.setFocusable(false);
        panRecordPagos.add(lblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 20));
        lblSalario.setVisible(false);

        lblTipoDeMoneda.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblTipoDeMoneda.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoDeMoneda.setText("Tipo de moneda:");
        lblTipoDeMoneda.setFocusable(false);
        panRecordPagos.add(lblTipoDeMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 20));
        lblTipoDeMoneda.setVisible(false);

        lblMesConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblMesConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lblMesConsultar.setText("Seleccionar mes a consultar:");
        lblMesConsultar.setFocusable(false);
        lblMesConsultar.setVisible(false);
        panRecordPagos.add(lblMesConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        cmbboxMesConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbboxMesConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbboxMesConsultar.setVisible(false);
        cmbboxMesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxMesConsultarActionPerformed(evt);
            }
        });
        cmbboxMesConsultar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbboxMesConsultarPropertyChange(evt);
            }
        });
        panRecordPagos.add(cmbboxMesConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, 20));

        btnConsultarMes.setBackground(new java.awt.Color(255, 153, 0));
        btnConsultarMes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConsultarMes.setText("Consultar");
        btnConsultarMes.setFocusable(false);
        btnConsultarMes.setVisible(false);
        btnConsultarMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMesMouseEntered(evt);
            }
        });
        btnConsultarMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMesActionPerformed(evt);
            }
        });
        panRecordPagos.add(btnConsultarMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblHorasLaborables.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblHorasLaborables.setForeground(new java.awt.Color(255, 255, 255));
        lblHorasLaborables.setText("Horas laborables del mes:");
        lblHorasLaborables.setFocusable(false);
        panRecordPagos.add(lblHorasLaborables, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, 20));
        lblHorasLaborables.setVisible(false);

        txtHorasLaborables.setEditable(false);
        txtHorasLaborables.setBackground(new java.awt.Color(204, 204, 204));
        txtHorasLaborables.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtHorasLaborables.setFocusable(false);
        txtHorasLaborables.setVisible(false);
        panRecordPagos.add(txtHorasLaborables, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 80, -1));

        tableReporteMes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableReporteMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Horas trabajadas", "Tipo de pago", "Monto pagado", "Tipo de moneda", "Proyecto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanReporteMes.setViewportView(tableReporteMes);

        panRecordPagos.add(scrollpanReporteMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 990, 390));
        scrollpanReporteMes.setVisible(false);

        getContentPane().add(panRecordPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1011, 580));

        jpanEncabezado1.setBackground(new java.awt.Color(255, 153, 51));
        jpanEncabezado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarCandidato1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblRegistrarCandidato1.setText("CONSULTAR RECORD DE PAGOS");
        jpanEncabezado1.add(lblRegistrarCandidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 22, -1, -1));

        getContentPane().add(jpanEncabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1011, 80));

        setSize(new java.awt.Dimension(1027, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtnProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnProyectoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnProyectoActionPerformed

    private void radiobtnProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnProyectoMouseClicked
       // TODO add your handling code here:
       
     /*  cmbboxProyectoConsultar.setVisible(true)
       *btnConsultarProyecto.setVisible(true); 
      * lblNombreProyectoConsultar.setVisible(true);
       
       *lblNombreEmpleadoConsultar.setVisible(false);
      * cmbboxEmpleadoConsultar.setVisible(false);
      * btnConsultarEmpleado.setVisible(false);
      * scrollpanReporteEmpleado.setVisible(false);
      * txtSalario.setVisible(false);
       *txtTipoDePago.setVisible(false);
       *txtTipoDeMoneda.setVisible(false);
       *lblSalario.setVisible(false);
      * lblTipoDePago.setVisible(false);
      * lblTipoDeMoneda.setVisible(false);
       
      * lblMesConsultar.setVisible(false);
      * cmbboxMesConsultar.setVisible(false);
      * btnConsultarMes.setVisible(false);
      * lblHorasLaborables.setVisible(false);    
      * txtHorasLaborables.setVisible(false);
      *  scrollpaneReporteMes.setVisible(false);
       */
    }//GEN-LAST:event_radiobtnProyectoMouseClicked

    private void radiobtnProyectoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiobtnProyectoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnProyectoStateChanged

    private void radiobtnEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnEmpleadoMouseClicked
        // TODO add your handling code here:
       
     /*  cmbboxProyectoConsultar.setVisible(false);
       
      * btnConsultarProyecto.setVisible(false); 
      * lblNombreProyectoConsultar.setVisible(false);
      * scrollpanReporteProyecto.setVisible(false);
       
       
      * lblNombreEmpleadoConsultar.setVisible(true);
      * cmbboxEmpleadoConsultar.setVisible(true);
      * btnConsultarEmpleado.setVisible(true);
       
      * lblMesConsultar.setVisible(false);
      * cmbboxMesConsultar.setVisible(false);
      * btnConsultarMes.setVisible(false);
      * lblHorasLaborables.setVisible(false);    
      * txtHorasLaborables.setVisible(false);
      * scrollpaneReporteMes.setVisible(false);
      */ 
    }//GEN-LAST:event_radiobtnEmpleadoMouseClicked

    private void radiobtnMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnMesMouseClicked
        // TODO add your handling code here:
       
       /*cmbboxProyectoConsultar.setVisible(false);
       *btnConsultarProyecto.setVisible(false); 
       *lblNombreProyectoConsultar.setVisible(false);
       *scrollpanReporteProyecto.setVisible(false);
     
       
       *lblNombreEmpleadoConsultar.setVisible(false);
       *cmbboxEmpleadoConsultar.setVisible(false);
       *btnConsultarEmpleado.setVisible(false);
       *scrollpanReporteEmpleado.setVisible(false);
       *txtSalario.setVisible(false);
       *txtTipoDePago.setVisible(false);
      * txtTipoDeMoneda.setVisible(false);
      * lblSalario.setVisible(false);
      * lblTipoDePago.setVisible(false);
      * lblTipoDeMoneda.setVisible(false);
       
      * lblMesConsultar.setVisible(true);
      * cmbboxMesConsultar.setVisible(true);
      * btnConsultarMes.setVisible(true);
        */
    }//GEN-LAST:event_radiobtnMesMouseClicked

    private void btnConsultarProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarProyectoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnConsultarProyectoMouseClicked

    private void btnConsultarProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarProyectoMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnConsultarProyectoMouseEntered

    private void btnConsultarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProyectoActionPerformed
        // TODO add your handling code here:
         //scrollpanReporteProyecto.setVisible(true);
    }//GEN-LAST:event_btnConsultarProyectoActionPerformed

    private void btnConsultarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEmpleadoMouseClicked

    private void btnConsultarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarEmpleadoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarEmpleadoMouseEntered

    private void btnConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpleadoActionPerformed
        // TODO add your handling code here:
       // scrollpanReporteEmpleado.setVisible(true);
    }//GEN-LAST:event_btnConsultarEmpleadoActionPerformed

    private void cmbboxProyectoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxProyectoConsultarActionPerformed
     // scrollpanReporteProyecto.setVisible(false);     // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbboxProyectoConsultarActionPerformed

    private void cmbboxEmpleadoConsultarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbboxEmpleadoConsultarPropertyChange
       // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxEmpleadoConsultarPropertyChange

    private void cmbboxProyectoConsultarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbboxProyectoConsultarPropertyChange
     // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxProyectoConsultarPropertyChange

    private void cmbboxEmpleadoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxEmpleadoConsultarActionPerformed
     /*  scrollpanReporteEmpleado.setVisible(false);
       txtSalario.setVisible(true);
       txtTipoDePago.setVisible(true);
       txtTipoDeMoneda.setVisible(true);
       lblSalario.setVisible(true);
       lblTipoDePago.setVisible(true);
       lblTipoDeMoneda.setVisible(true);
        */
// TODO add your handling code here:
    }//GEN-LAST:event_cmbboxEmpleadoConsultarActionPerformed

    private void cmbboxMesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxMesConsultarActionPerformed
/*lblHorasLaborables.setVisible(true);    
txtHorasLaborables.setVisible(true);
scrollpanReporteMes.setVisible(false);// TODO add your handling code here:
        */
    }//GEN-LAST:event_cmbboxMesConsultarActionPerformed

    private void cmbboxMesConsultarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbboxMesConsultarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxMesConsultarPropertyChange

    private void btnConsultarMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMesMouseClicked

    private void btnConsultarMesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMesMouseEntered

    private void btnConsultarMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMesActionPerformed
//scrollpanReporteMes.setVisible(true);        // TODO add your handling code here: 
    }//GEN-LAST:event_btnConsultarMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VConsultaRecordPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarEmpleado;
    private javax.swing.JButton btnConsultarMes;
    private javax.swing.JButton btnConsultarProyecto;
    private javax.swing.ButtonGroup btngroupFiltrarPor;
    private javax.swing.JComboBox<String> cmbboxEmpleadoConsultar;
    private javax.swing.JComboBox<String> cmbboxMesConsultar;
    private javax.swing.JComboBox<String> cmbboxProyectoConsultar;
    private javax.swing.JPanel jpanEncabezado;
    private javax.swing.JPanel jpanEncabezado1;
    private javax.swing.JLabel lblFiltrarPor;
    private javax.swing.JLabel lblHorasLaborables;
    private javax.swing.JLabel lblMesConsultar;
    private javax.swing.JLabel lblNombreEmpleadoConsultar;
    private javax.swing.JLabel lblNombreProyectoConsultar;
    private javax.swing.JLabel lblRegistrarCandidato;
    private javax.swing.JLabel lblRegistrarCandidato1;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTipoDeMoneda;
    private javax.swing.JLabel lblTipoDePago;
    private javax.swing.JPanel panRecordPagos;
    private javax.swing.JRadioButton radiobtnEmpleado;
    private javax.swing.JRadioButton radiobtnMes;
    private javax.swing.JRadioButton radiobtnProyecto;
    private javax.swing.JScrollPane scrollpanReporteEmpleado;
    private javax.swing.JScrollPane scrollpanReporteMes;
    private javax.swing.JScrollPane scrollpanReporteProyecto;
    private javax.swing.JTable tableReporteEmpleado;
    private javax.swing.JTable tableReporteMes;
    private javax.swing.JTable tableReporteProyecto;
    private javax.swing.JTextField txtHorasLaborables;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTipoDeMoneda;
    private javax.swing.JTextField txtTipoDePago;
    // End of variables declaration//GEN-END:variables
}
