/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ABUNASSAR PENARANDA
 */
public class VConsultaRecordUtilidad extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarRecordUtilidad
     */
    public VConsultaRecordUtilidad() {
        initComponents();
        
        
    }

    public JButton getBtnConsultarMes() {
        return btnConsultarMes;
    }

    public JButton getBtnConsultarProyecto() {
        return btnConsultarProyecto;
    }

    public ButtonGroup getBtngroupFiltrarPor() {
        return btngroupFiltrarPor;
    }

    public JComboBox<String> getCmbboxMesConsultar() {
        return cmbboxMesConsultar;
    }

    public JComboBox<String> getCmbboxProyectoConsultar() {
        return cmbboxProyectoConsultar;
    }

    public JLabel getLblFiltrarPor() {
        return lblFiltrarPor;
    }

    public JLabel getLblHorasLaborables() {
        return lblHorasLaborables;
    }

    public JLabel getLblMesConsultar() {
        return lblMesConsultar;
    }

    public JLabel getLblNombreProyectoConsultar() {
        return lblNombreProyectoConsultar;
    }


    public JPanel getPanConsultarUtilidad() {
        return panConsultarUtilidad;
    }

    public JRadioButton getRadiobtnMes() {
        return radiobtnMes;
    }

    public JRadioButton getRadiobtnProyecto() {
        return radiobtnProyecto;
    }

    public JScrollPane getScrollpanReporteProyecto() {
        return scrollpanReporteProyecto;
    }

    public JScrollPane getScrollpaneReporteMes() {
        return scrollpaneReporteMes;
    }

    public JTable getTableReporteMes() {
        return tableReporteMes;
    }

    public JTable getTableReporteProyecto() {
        return tableReporteProyecto;
    }

    public JTextField getTxtHorasLaborables() {
        return txtHorasLaborables;
    }
    
     public void Agregar_Listener(ActionListener ac)
   {
   
       this.radiobtnProyecto.addActionListener(ac);
       this.radiobtnMes.addActionListener(ac);
       this.cmbboxProyectoConsultar.addActionListener(ac);
       this.cmbboxMesConsultar.addActionListener(ac);
       this.btnConsultarProyecto.addActionListener(ac);
       this.btnConsultarMes.addActionListener(ac);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupFiltrarPor = new javax.swing.ButtonGroup();
        panConsultarUtilidad = new javax.swing.JPanel();
        lblFiltrarPor = new javax.swing.JLabel();
        radiobtnProyecto = new javax.swing.JRadioButton();
        radiobtnMes = new javax.swing.JRadioButton();
        cmbboxProyectoConsultar = new javax.swing.JComboBox<>();
        btnConsultarProyecto = new javax.swing.JButton();
        lblNombreProyectoConsultar = new javax.swing.JLabel();
        cmbboxMesConsultar = new javax.swing.JComboBox<>();
        btnConsultarMes = new javax.swing.JButton();
        lblHorasLaborables = new javax.swing.JLabel();
        txtHorasLaborables = new javax.swing.JTextField();
        lblMesConsultar = new javax.swing.JLabel();
        scrollpanReporteProyecto = new javax.swing.JScrollPane();
        tableReporteProyecto = new javax.swing.JTable();
        scrollpaneReporteMes = new javax.swing.JScrollPane();
        tableReporteMes = new javax.swing.JTable();
        jpanEncabezado1 = new javax.swing.JPanel();
        lblRegistrarCandidato1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panConsultarUtilidad.setBackground(new java.awt.Color(102, 102, 102));
        panConsultarUtilidad.setForeground(new java.awt.Color(102, 102, 102));
        panConsultarUtilidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFiltrarPor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFiltrarPor.setForeground(new java.awt.Color(255, 255, 255));
        lblFiltrarPor.setText("Filtrar por:");
        panConsultarUtilidad.add(lblFiltrarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 38, -1, -1));

        radiobtnProyecto.setBackground(new java.awt.Color(102, 102, 102));
        btngroupFiltrarPor.add(radiobtnProyecto);
        radiobtnProyecto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radiobtnProyecto.setForeground(new java.awt.Color(255, 255, 255));
        radiobtnProyecto.setText("Proyecto");
        radiobtnProyecto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiobtnProyectoStateChanged(evt);
            }
        });
        radiobtnProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnProyectoMouseClicked(evt);
            }
        });
        radiobtnProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnProyectoActionPerformed(evt);
            }
        });
        //radiobtnProyecto.setSelected(true);
        panConsultarUtilidad.add(radiobtnProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 56, -1, -1));

        radiobtnMes.setBackground(new java.awt.Color(102, 102, 102));
        btngroupFiltrarPor.add(radiobtnMes);
        radiobtnMes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        radiobtnMes.setForeground(new java.awt.Color(255, 255, 255));
        radiobtnMes.setText("Mes");
        radiobtnMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnMesMouseClicked(evt);
            }
        });
        panConsultarUtilidad.add(radiobtnMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 56, -1, -1));

        cmbboxProyectoConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbboxProyectoConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cmbboxProyectoConsultar.setVisible(false);
        cmbboxProyectoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxProyectoConsultarActionPerformed(evt);
            }
        });
        cmbboxProyectoConsultar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbboxProyectoConsultarPropertyChange(evt);
            }
        });
        panConsultarUtilidad.add(cmbboxProyectoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 300, 20));

        btnConsultarProyecto.setBackground(new java.awt.Color(255, 102, 0));
        btnConsultarProyecto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConsultarProyecto.setText("Consultar");
        btnConsultarProyecto.setVisible(false);
        btnConsultarProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarProyectoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarProyectoMouseEntered(evt);
            }
        });
        btnConsultarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProyectoActionPerformed(evt);
            }
        });
        panConsultarUtilidad.add(btnConsultarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblNombreProyectoConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblNombreProyectoConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProyectoConsultar.setText("Nombre del proyecto a consultar:");
        lblNombreProyectoConsultar.setVisible(false);
        panConsultarUtilidad.add(lblNombreProyectoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmbboxMesConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbboxMesConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbboxMesConsultar.setVisible(false);
        cmbboxMesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxMesConsultarActionPerformed(evt);
            }
        });
        cmbboxMesConsultar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbboxMesConsultarPropertyChange(evt);
            }
        });
        panConsultarUtilidad.add(cmbboxMesConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, 20));

        btnConsultarMes.setBackground(new java.awt.Color(255, 102, 0));
        btnConsultarMes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConsultarMes.setText("Consultar");
        btnConsultarMes.setVisible(false);
        btnConsultarMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultarMesMouseEntered(evt);
            }
        });
        btnConsultarMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMesActionPerformed(evt);
            }
        });
        panConsultarUtilidad.add(btnConsultarMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblHorasLaborables.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblHorasLaborables.setForeground(new java.awt.Color(255, 255, 255));
        lblHorasLaborables.setText("Horas laborables del mes:");
        panConsultarUtilidad.add(lblHorasLaborables, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, 20));
        lblHorasLaborables.setVisible(false);

        txtHorasLaborables.setEditable(false);
        txtHorasLaborables.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtHorasLaborables.setFocusable(false);
        txtHorasLaborables.setVisible(false);
        panConsultarUtilidad.add(txtHorasLaborables, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 80, -1));

        lblMesConsultar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblMesConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lblMesConsultar.setText("Seleccionar mes a consultar:");
        lblMesConsultar.setVisible(false);
        panConsultarUtilidad.add(lblMesConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        scrollpanReporteProyecto.setVisible(false);

        tableReporteProyecto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableReporteProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ingresos", "Egresos", "Utilidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpanReporteProyecto.setViewportView(tableReporteProyecto);

        panConsultarUtilidad.add(scrollpanReporteProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 990, 70));

        tableReporteMes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tableReporteMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingresos", "Egresos", "Utilidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneReporteMes.setViewportView(tableReporteMes);

        panConsultarUtilidad.add(scrollpaneReporteMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 990, 70));
        scrollpaneReporteMes.setVisible(false);

        getContentPane().add(panConsultarUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1019, 310));

        jpanEncabezado1.setBackground(new java.awt.Color(255, 153, 51));
        jpanEncabezado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistrarCandidato1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        lblRegistrarCandidato1.setText("CONSULTAR RECORD DE PAGOS");
        jpanEncabezado1.add(lblRegistrarCandidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 22, -1, -1));

        getContentPane().add(jpanEncabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1019, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobtnProyectoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiobtnProyectoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnProyectoStateChanged

    private void radiobtnProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnProyectoMouseClicked
        // TODO add your handling code here:

       /* cmbboxProyectoConsultar.setVisible(true);
        btnConsultarProyecto.setVisible(true);
        lblNombreProyectoConsultar.setVisible(true);

       

        lblMesConsultar.setVisible(false);
        cmbboxMesConsultar.setVisible(false);
        btnConsultarMes.setVisible(false);
        lblHorasLaborables.setVisible(false);
        txtHorasLaborables.setVisible(false);
        scrollpaneReporteMes.setVisible(false);
        */
    }//GEN-LAST:event_radiobtnProyectoMouseClicked

    private void radiobtnProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnProyectoActionPerformed

    private void radiobtnMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnMesMouseClicked
        // TODO add your handling code here:

       /* cmbboxProyectoConsultar.setVisible(false);
        btnConsultarProyecto.setVisible(false);
        lblNombreProyectoConsultar.setVisible(false);
        scrollpanReporteProyecto.setVisible(false);

        

        lblMesConsultar.setVisible(true);
        cmbboxMesConsultar.setVisible(true);
        btnConsultarMes.setVisible(true);*/
    }//GEN-LAST:event_radiobtnMesMouseClicked

    private void cmbboxProyectoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxProyectoConsultarActionPerformed
       // scrollpanReporteProyecto.setVisible(false);     // TODO add your handling code here:

    }//GEN-LAST:event_cmbboxProyectoConsultarActionPerformed

    private void cmbboxProyectoConsultarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbboxProyectoConsultarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxProyectoConsultarPropertyChange

    private void btnConsultarProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarProyectoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnConsultarProyectoMouseClicked

    private void btnConsultarProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarProyectoMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnConsultarProyectoMouseEntered

    private void btnConsultarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProyectoActionPerformed
        // TODO add your handling code here:
      //  scrollpanReporteProyecto.setVisible(true);
    }//GEN-LAST:event_btnConsultarProyectoActionPerformed

    private void cmbboxMesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxMesConsultarActionPerformed
       /* lblHorasLaborables.setVisible(true);
        txtHorasLaborables.setVisible(true);
        scrollpaneReporteMes.setVisible(false);*/// TODO add your handling code here:
    }//GEN-LAST:event_cmbboxMesConsultarActionPerformed

    private void cmbboxMesConsultarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbboxMesConsultarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxMesConsultarPropertyChange

    private void btnConsultarMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMesMouseClicked

    private void btnConsultarMesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMesMouseEntered

    private void btnConsultarMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMesActionPerformed
      //  scrollpaneReporteMes.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordUtilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordUtilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordUtilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VConsultaRecordUtilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VConsultaRecordUtilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarMes;
    private javax.swing.JButton btnConsultarProyecto;
    private javax.swing.ButtonGroup btngroupFiltrarPor;
    private javax.swing.JComboBox<String> cmbboxMesConsultar;
    private javax.swing.JComboBox<String> cmbboxProyectoConsultar;
    private javax.swing.JPanel jpanEncabezado1;
    private javax.swing.JLabel lblFiltrarPor;
    private javax.swing.JLabel lblHorasLaborables;
    private javax.swing.JLabel lblMesConsultar;
    private javax.swing.JLabel lblNombreProyectoConsultar;
    private javax.swing.JLabel lblRegistrarCandidato1;
    private javax.swing.JPanel panConsultarUtilidad;
    private javax.swing.JRadioButton radiobtnMes;
    private javax.swing.JRadioButton radiobtnProyecto;
    private javax.swing.JScrollPane scrollpanReporteProyecto;
    private javax.swing.JScrollPane scrollpaneReporteMes;
    private javax.swing.JTable tableReporteMes;
    private javax.swing.JTable tableReporteProyecto;
    private javax.swing.JTextField txtHorasLaborables;
    // End of variables declaration//GEN-END:variables
}
