/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Vicky
 */
public class VRegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form VRegistroCliente
     */
    public VRegistroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtRifCliente = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtCodTelf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelfCliente = new javax.swing.JTextField();
        txtNomCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbIdioma = new javax.swing.JComboBox<>();
        txtTitProy = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescProy = new javax.swing.JTextArea();
        DTPFechaFinal = new com.toedter.calendar.JDateChooser();
        DTPFechaIni = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JetManager- Registrar Cliente");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setLabelFor(txtCorreo);
        jLabel1.setText("Rif");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre o Razón Social");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtCorreo.setName("txtCorreo"); // NOI18N
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 290, 30));

        txtCiudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtCiudad.setName("txtRifCliente"); // NOI18N
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 110, 30));

        txtPais.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPais.setName("txtRifCliente"); // NOI18N
        txtPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaisActionPerformed(evt);
            }
        });
        jPanel1.add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 30));

        txtRifCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRifCliente.setName("txtRifCliente"); // NOI18N
        jPanel1.add(txtRifCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 140, 30));

        btnSiguiente.setBackground(new java.awt.Color(255, 153, 51));
        btnSiguiente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 20));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("País");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ciudad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 290, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("J-");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        txtCodTelf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(txtCodTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 80, 30));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        txtTelfCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(txtTelfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 170, 30));

        txtNomCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtNomCliente.setName("txtRifCliente"); // NOI18N
        jPanel1.add(txtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 200, 30));

        jTabbedPane1.addTab("Cliente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(255, 153, 51));
        btnAgregar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 90, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Título");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descripción");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de Inicio");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fecha Final");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Idioma");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        cmbIdioma.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Inglés", "Español", "Otro.." }));
        jPanel2.add(cmbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        txtTitProy.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(txtTitProy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 380, 30));

        txtDescProy.setColumns(20);
        txtDescProy.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDescProy.setRows(5);
        jScrollPane2.setViewportView(txtDescProy);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 380, -1));

        DTPFechaFinal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(DTPFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 140, 30));

        DTPFechaIni.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(DTPFechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 140, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Proyecto", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("tabProyecto");

        btnCancelar.setBackground(new java.awt.Color(255, 153, 51));
        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tabPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
this.jPanel2.show();        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRegistroCliente().setVisible(true);
            }
        });
    }

    public JDateChooser getDTPFechaFinal() {
        return DTPFechaFinal;
    }

    public void setDTPFechaFinal(JDateChooser DTPFechaFinal) {
        this.DTPFechaFinal = DTPFechaFinal;
    }

    public JDateChooser getDTPFechaIni() {
        return DTPFechaIni;
    }

    public void setDTPFechaIni(JDateChooser DTPFechaIni) {
        this.DTPFechaIni = DTPFechaIni;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }


    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JComboBox<String> getCmbIdioma() {
        return cmbIdioma;
    }

    public void setCmbIdioma(JComboBox<String> cmbIdioma) {
        this.cmbIdioma = cmbIdioma;
    }

    public JTextField getTxtCiudad() {
        return txtCiudad;
    }

    public void setTxtCiudad(JTextField txtCiudad) {
        this.txtCiudad = txtCiudad;
    }

    public JTextField getTxtCodTelf() {
        return txtCodTelf;
    }

    public void setTxtCodTelf(JTextField txtCodTelf) {
        this.txtCodTelf = txtCodTelf;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }

    public JTextArea getTxtDescProy() {
        return txtDescProy;
    }

    public void setTxtDescProy(JTextArea txtDescProy) {
        this.txtDescProy = txtDescProy;
    }

    public JTextArea getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextArea txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtNomCliente() {
        return txtNomCliente;
    }

    public void setTxtNomCliente(JTextField txtNomCliente) {
        this.txtNomCliente = txtNomCliente;
    }



    public JTextField getTxtPais() {
        return txtPais;
    }

    public void setTxtPais(JTextField txtPais) {
        this.txtPais = txtPais;
    }

    public JTextField getTxtRifCliente() {
        return txtRifCliente;
    }

    public void setTxtRifCliente(JTextField txtRifCliente) {
        this.txtRifCliente = txtRifCliente;
    }

    public JTextField getTxtTelfCliente() {
        return txtTelfCliente;
    }

    public void setTxtTelfCliente(JTextField txtTelfCliente) {
        this.txtTelfCliente = txtTelfCliente;
    }

    public JTextField getTxtTitProy() {
        return txtTitProy;
    }

    public void setTxtTitProy(JTextField txtTitProy) {
        this.txtTitProy = txtTitProy;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DTPFechaFinal;
    private com.toedter.calendar.JDateChooser DTPFechaIni;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodTelf;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDescProy;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRifCliente;
    private javax.swing.JTextField txtTelfCliente;
    private javax.swing.JTextField txtTitProy;
    // End of variables declaration//GEN-END:variables

public void agregarListener(ActionListener accion){
    this.btnAgregar.addActionListener(accion);
    this.btnCancelar.addActionListener(accion);
    
}

}
